/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#131316',
        'surface-dim': '#131316',
        'surface-bright': '#39393c',
        'surface-container-lowest': '#0e0e11',
        'surface-container-low': '#1b1b1e',
        'surface-container': '#1f1f22',
        'surface-container-high': '#2a2a2d',
        'surface-container-highest': '#353438',
        'on-surface': '#e4e1e6',
        'on-surface-variant': '#d0c2d5',
        'inverse-surface': '#e4e1e6',
        'inverse-on-surface': '#303033',
        outline: '#998d9e',
        'outline-variant': '#4d4353',
        'surface-tint': '#e0b6ff',
        primary: '#e0b6ff',
        'on-primary': '#4c007d',
        'primary-container': '#9d4edd',
        'on-primary-container': '#fffdff',
        'inverse-primary': '#8433c4',
        secondary: '#e1b6ff',
        'on-secondary': '#4c007b',
        'secondary-container': '#691a9f',
        'on-secondary-container': '#d69eff',
        tertiary: '#edc156',
        'on-tertiary': '#3f2e00',
        'tertiary-container': '#947000',
        'on-tertiary-container': '#fffdff',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#f2daff',
        'primary-fixed-dim': '#e0b6ff',
        'on-primary-fixed': '#2e004e',
        'on-primary-fixed-variant': '#6a0baa',
        'secondary-fixed': '#f2daff',
        'secondary-fixed-dim': '#e1b6ff',
        'on-secondary-fixed': '#2e004d',
        'on-secondary-fixed-variant': '#691a9f',
        'tertiary-fixed': '#ffdf9a',
        'tertiary-fixed-dim': '#edc156',
        'on-tertiary-fixed': '#251a00',
        'on-tertiary-fixed-variant': '#5a4300',
        background: '#131316',
        'on-background': '#e4e1e6',
        'surface-variant': '#353438',
        'surface-charcoal': '#1E1E24',
        'success-green': '#2ECC71',
        'warning-orange': '#F39C12',
        'rank-gold': '#FFD700',
        'text-muted': '#A0A0AB',
        'border-subtle': '#2D2D35',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '16px',
        'margin-mobile': '20px',
        'margin-desktop': 'auto',
      },
      maxWidth: {
        'max-width': '1200px',
      },
    },
  },
  plugins: [],
}